# Generated by Django 3.1.5 on 2022-08-26 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50, verbose_name='category name ')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50, verbose_name='name')),
                ('pro_type', models.BooleanField(verbose_name='type')),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('pro_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='discount')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='total price')),
                ('pro_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand', verbose_name='brand name')),
                ('pro_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_size', models.CharField(max_length=50, verbose_name='size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='title')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pro_size',
            field=models.ManyToManyField(related_name='product_size', through='product.ProductSize', to='product.Size', verbose_name='size'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im_photo', models.ImageField(upload_to='image', verbose_name='image')),
                ('im_url', models.URLField(max_length=500, verbose_name='url')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product')),
            ],
        ),
    ]
