# Generated by Django 3.1.5 on 2022-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_pro_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
