# Generated by Django 3.1.5 on 2022-08-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220827_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_type',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
