# Generated by Django 3.1.5 on 2022-08-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220827_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_discount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_price',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_total_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='total price'),
        ),
    ]
