# Generated by Django 3.1.5 on 2022-08-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220827_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='total price'),
        ),
    ]
