# Generated by Django 3.1.5 on 2022-08-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=50, verbose_name='status'),
        ),
    ]
