# Generated by Django 3.1.5 on 2022-08-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220828_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_size', models.IntegerField(verbose_name='size')),
            ],
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='size',
            new_name='cl_size',
        ),
        migrations.AddField(
            model_name='productsize',
            name='sh_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.shoessize', verbose_name='size'),
        ),
    ]
