# Generated by Django 3.1.5 on 2022-09-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220828_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
