# Generated by Django 3.1.5 on 2022-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=11, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
