# Generated by Django 3.1.5 on 2022-09-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220905_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default=1, max_length=6, verbose_name='size'),
            preserve_default=False,
        ),
    ]
